version: '3.1'

services:

  web:
    build: 
      context: .
      dockerfile: ./.docker/web/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - mysql

  mysql:
    image: tugboatqa/mysql:5.6
    restart: always
    volumes: 
      - mysql_data:/var/lib/mysql
    ports:
      - 33065:3306

volumes: 
  mysql_data: